# -*- coding: utf-8 -*-
"""Final IMP 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/munamj/final-imp-3.82c62ca1-f8be-4574-a1c8-19ba46bac9c6.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260301/auto/storage/goog4_request%26X-Goog-Date%3D20260301T063810Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D33de862b7e65c166abbb8ce209ce5fd3695aed9682065ed693b013a47f8beb64dd9b0fd1055d5b0ac2e4844769d91128f3c2d27d2c0fdca4bf5d89ea617100f2a7e10645a0bcf4d89b1b3f8911cf377e56edbce693d573bf2ac373dab03d756b77cd0a4f42526f5d728532d1d7595ba5d28c8c0678abe60d4881db57858b84e27c677767830dc81e04e1fa48b7a90d2496906165887e57c10072755165b8542547ea3812d86d48b10ad07fa857d7028c5a9bcb534b9ecdb8e35ec992a198c28dcb106fba2df671ecec39a2a51d1058fa6c7b7a2d77100df5203e6fe58292620a0a3db41203e2d3d6f56172dae174b78224f229b6b5635cf44e591256325fff3a
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
mathurinache_cmu_mosi_path = kagglehub.dataset_download('mathurinache/cmu-mosi')

print('Data source import complete.')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import os
import warnings
warnings.filterwarnings('ignore')
import math
import random
import cv2
import librosa
import pickle
import json
from glob import glob
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from torch.optim.lr_scheduler import ReduceLROnPlateau
import gc


class Config:
    # Model parameters
    HIDDEN_DIM = 256
    NUM_HEADS = 8
    FF_DIM = 512
    LATENT_DIM = 256
    LATENT_DIM_VAE = 128
    NUM_EMOTIONS = 6
    DROPOUT = 0.2

    # Feature dim
    VISUAL_FEAT_DIM = 256
    AUDIO_FEAT_DIM = 256
    TEXT_FEAT_DIM = 256

    # Loss weights
    VAE_WEIGHT = 1.0
    GAN_WEIGHT = 0.5
    SEQDIS_WEIGHT = 1.0
    CYCLE_WEIGHT = 5.0

    # Training parameters
    BATCH_SIZE = 16
    LEARNING_RATE = 0.0001
    NUM_EPOCHS = 10
    GRADIENT_CLIP = 1.0
    E2E_RATIO = 7

    # Dataset parameters
    MAX_SEQ_LEN = 30
    SAMPLE_RATE = 16000
    MAX_AUDIO_DURATION = 4.0

    BASE_PATH = '/kaggle/input/datasets/mathurinache/cmu-mosi'
    CACHE_DIR = './feature_cache'

    # Device
    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

config = Config()
print(f"Using device: {config.DEVICE}")
print(f"Dataset path: {config.BASE_PATH}")
print(f"E2E Ratio: 1:{config.E2E_RATIO}")

os.makedirs(config.CACHE_DIR, exist_ok=True)


class CMUMOSIDataset(Dataset):
    def __init__(self, base_path, split='train', max_seq_len=30, transform=None):
        self.base_path = base_path
        self.split = split
        self.max_seq_len = max_seq_len
        self.transform = transform

        # Emotion mapping (labels - placeholder)
        self.emotion_to_idx = {
            'happy': 0, 'sad': 1, 'anger': 2,
            'surprise': 3, 'disgust': 4, 'fear': 5
        }

        # Load all video files
        self.video_files = self._collect_video_files()
        print(f"Found {len(self.video_files)} total video files")

        # Create splits (70-15-15)
        self._create_splits()

        print(f"Created {split} split with {len(self)} samples")

    def _collect_video_files(self):
        video_files = []
        video_dirs = [
            os.path.join(self.base_path, 'Raw', 'Video', 'Full'),
            os.path.join(self.base_path, 'Raw', 'Video', 'Segmented')
        ]

        for video_dir in video_dirs:
            if os.path.exists(video_dir):
                print(f"Scanning: {video_dir}")
                for file in os.listdir(video_dir):
                    if file.endswith('.mp4'):
                        video_path = os.path.join(video_dir, file)
                        video_id = file.replace('.mp4', '')

                        audio_path = self._find_audio_file(video_id)
                        transcript_path = self._find_transcript_file(video_id)

                        label = self._get_label(video_id)

                        video_files.append({
                            'video_id': video_id,
                            'video_path': video_path,
                            'audio_path': audio_path,
                            'transcript_path': transcript_path,
                            'label': label
                        })

        return video_files

    def _find_audio_file(self, video_id):
        audio_dirs = [
            os.path.join(self.base_path, 'Raw', 'Audio', 'WAV_16000'),
            os.path.join(self.base_path, 'Raw', 'Audio', 'WAV_11025')
        ]

        for audio_dir in audio_dirs:
            if os.path.exists(audio_dir):
                for ext in ['.wav', '.mp3']:
                    audio_path = os.path.join(audio_dir, f"{video_id}{ext}")
                    if os.path.exists(audio_path):
                        return audio_path

                    audio_path = os.path.join(audio_dir, f"{video_id}")
                    if os.path.exists(audio_path):
                        return audio_path

        return None

    def _find_transcript_file(self, video_id):
        transcript_dirs = [
            os.path.join(self.base_path, 'Raw', 'Transcript', 'Full'),
            os.path.join(self.base_path, 'Raw', 'Transcript', 'Segmented')
        ]

        for trans_dir in transcript_dirs:
            if os.path.exists(trans_dir):
                for ext in ['.txt', '.textonly', '.annotprocessed', '']:
                    trans_path = os.path.join(trans_dir, f"{video_id}{ext}")
                    if os.path.exists(trans_path):
                        return trans_path

        return None

    def _create_splits(self):
        random.shuffle(self.video_files)
        n = len(self.video_files)

        train_end = int(n * 0.7)
        val_end = int(n * 0.85)

        if self.split == 'train':
            self.samples = self.video_files[:train_end]
        elif self.split == 'val':
            self.samples = self.video_files[train_end:val_end]
        else:  # test
            self.samples = self.video_files[val_end:]

    def _get_label(self, video_id):
        label_file = os.path.join(self.base_path, 'labels.json')
        if os.path.exists(label_file):
            with open(label_file, 'r') as f:
                labels = json.load(f)
                return labels.get(video_id, 0)

        return abs(hash(video_id)) % config.NUM_EMOTIONS

    def _extract_frames(self, video_path):
        frames = []
        cap = cv2.VideoCapture(video_path)

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            cap.release()
            return np.zeros((self.max_seq_len, 224, 224, 3))

        indices = np.linspace(0, total_frames-1, self.max_seq_len, dtype=int)

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()
            if ret:
                frame = cv2.resize(frame, (224, 224))
                frames.append(frame)
            else:
                frames.append(np.zeros((224, 224, 3)))

        cap.release()
        return np.array(frames)

    def _extract_audio(self, audio_path):
        try:
            audio, sr = librosa.load(audio_path, sr=config.SAMPLE_RATE)
            return audio
        except:
            return np.zeros(config.SAMPLE_RATE * 4)

    def _read_transcript(self, transcript_path):
        try:
            with open(transcript_path, 'r', encoding='utf-8', errors='ignore') as f:
                return f.read()
        except:
            return ""

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]

        return {
            'video_id': sample['video_id'],
            'video_path': sample['video_path'],
            'audio_path': sample['audio_path'],
            'transcript_path': sample['transcript_path'],
            'label': sample['label'],
            'text': torch.zeros(self.max_seq_len, config.TEXT_FEAT_DIM),  # Placeholder
            'visual': torch.zeros(self.max_seq_len, config.VISUAL_FEAT_DIM),  # Placeholder
            'audio': torch.zeros(self.max_seq_len, config.AUDIO_FEAT_DIM)  # Placeholder
        }


class FANFeatureExtractor:
    def __init__(self, device):
        self.device = device
        self.cnn = nn.Sequential(
            nn.Conv2d(3, 64, 3, 2, 1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 128, 3, 2, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, 256, 3, 2, 1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
            nn.Linear(256, config.VISUAL_FEAT_DIM)
        ).to(device)
        self.cnn.eval()
        print("FAN initialized")

    @torch.no_grad()
    def extract_video_features(self, video_path, max_frames=30):
        frames = []
        cap = cv2.VideoCapture(video_path)

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            return np.zeros((max_frames, config.VISUAL_FEAT_DIM))

        indices = np.linspace(0, total_frames-1, max_frames, dtype=int)

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()
            if ret:
                frame = cv2.resize(frame, (64, 64))
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                frame = frame.astype(np.float32) / 255.0
                frame_tensor = torch.FloatTensor(frame).permute(2, 0, 1).unsqueeze(0).to(self.device)

                features = self.cnn(frame_tensor)
                frames.append(features.cpu().numpy()[0])
            else:
                frames.append(np.zeros(config.VISUAL_FEAT_DIM))

        cap.release()

        while len(frames) < max_frames:
            frames.append(np.zeros(config.VISUAL_FEAT_DIM))

        return np.stack(frames)[:max_frames]


class PANNsFeatureExtractor:
    def __init__(self, device):
        self.device = device
        print("PANNs initialized")

    def extract_audio_features(self, audio_path, max_frames=30):
        try:
            audio, sr = librosa.load(audio_path, sr=config.SAMPLE_RATE)
            mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)

            # Pool to fixed length
            if mfccs.shape[1] > max_frames:
                indices = np.linspace(0, mfccs.shape[1]-1, max_frames, dtype=int)
                features = mfccs[:, indices].T
            else:
                features = np.zeros((max_frames, 40))
                features[:mfccs.shape[1], :] = mfccs.T

            # Project to target dim
            if features.shape[1] < config.AUDIO_FEAT_DIM:
                repeats = config.AUDIO_FEAT_DIM // features.shape[1] + 1
                features = np.tile(features, (1, repeats))[:, :config.AUDIO_FEAT_DIM]

            return features
        except:
            return np.zeros((max_frames, config.AUDIO_FEAT_DIM))


class GloVeFeatureExtractor:
    def __init__(self):
        self.embedding_dim = 300
        self.word_vectors = {}

        try:
            print("Using random embeddings (replace with actual GloVe)")
        except:
            pass
        print(" Text extractor initialized")

    def get_word_vector(self, word):
        np.random.seed(abs(hash(word)) % 2**32)
        return np.random.randn(self.embedding_dim) * 0.1

    def extract_text_features(self, text, max_words=30):
        words = text.lower().split()[:max_words]

        features = []
        for word in words:
            vec = self.get_word_vector(word)
            features.append(vec)

        while len(features) < max_words:
            features.append(np.zeros(self.embedding_dim))

        features = np.stack(features)

        # Project to target dim
        if features.shape[1] != config.TEXT_FEAT_DIM:
            if features.shape[1] < config.TEXT_FEAT_DIM:
                repeats = config.TEXT_FEAT_DIM // features.shape[1] + 1
                features = np.tile(features, (1, repeats))[:, :config.TEXT_FEAT_DIM]
            else:
                features = features[:, :config.TEXT_FEAT_DIM]

        return features


def collate_fn(batch):
    video_ids = [item['video_id'] for item in batch]
    video_paths = [item['video_path'] for item in batch]
    audio_paths = [item['audio_path'] for item in batch]
    transcript_paths = [item['transcript_path'] for item in batch]
    labels = torch.tensor([item['label'] for item in batch])

    text = torch.stack([item['text'] for item in batch])
    visual = torch.stack([item['visual'] for item in batch])
    audio = torch.stack([item['audio'] for item in batch])

    return {
        'text': text,
        'visual': visual,
        'audio': audio,
        'label': labels,
        'video_id': video_ids,
        'video_path': video_paths,
        'audio_path': audio_paths,
        'transcript_path': transcript_paths
    }


class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout=0.1, max_len=5000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return self.dropout(x + self.pe[:, :x.size(1), :])


class VAEEncoder(nn.Module):
    def __init__(self, input_dim, latent_dim=64, hidden_dim=128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.1),
            nn.Linear(hidden_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.LeakyReLU(0.2),
        )
        self.mu = nn.Linear(hidden_dim, latent_dim)
        self.logvar = nn.Linear(hidden_dim, latent_dim)

    def forward(self, x):
        h = self.net(x)
        return self.mu(h), self.logvar(h)


class VAEDecoder(nn.Module):
    def __init__(self, latent_dim, output_dim, hidden_dim=128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.1),
            nn.Linear(hidden_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim, output_dim)
        )

    def forward(self, z):
        return self.net(z)


class FrameDiscriminator(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.1),
            nn.Linear(64, 32),
            nn.LeakyReLU(0.2),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)


class SequenceDiscriminator(nn.Module):
    def __init__(self, feature_dim, num_classes=6, d_model=128, nhead=4):
        super().__init__()
        self.num_classes = num_classes
        self.num_total_classes = num_classes + 1

        self.input_proj = nn.Linear(feature_dim, d_model)
        self.pos_encoding = PositionalEncoding(d_model)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=d_model*2,
            dropout=0.1,
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)

        self.classifier = nn.Sequential(
            nn.Linear(d_model, d_model),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(d_model, self.num_total_classes)
        )

    def forward(self, x_seq):
        x = self.input_proj(x_seq)
        x = self.pos_encoding(x)
        x = self.transformer(x)
        x = x.mean(dim=1)
        logits = self.classifier(x)
        return logits


class VAEGANTranslator(nn.Module):
    def __init__(self, source_dim, target_dim, latent_dim=64, num_emotions=6,
                 shared_encoder=None, shared_decoder=None, name=""):
        super().__init__()
        self.source_dim = source_dim
        self.target_dim = target_dim
        self.latent_dim = latent_dim
        self.name = name

        if shared_encoder is not None:
            self.encoder = shared_encoder
        else:
            self.encoder = VAEEncoder(source_dim, latent_dim)

        if shared_decoder is not None:
            self.decoder = shared_decoder
        else:
            self.decoder = VAEDecoder(latent_dim, target_dim)

        self.frame_disc = FrameDiscriminator(target_dim)
        self.seq_disc = SequenceDiscriminator(target_dim, num_emotions)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def encode_sequence(self, x_seq):
        batch_size, seq_len, feat_dim = x_seq.shape
        x_flat = x_seq.reshape(-1, feat_dim)
        mu, logvar = self.encoder(x_flat)
        mu = mu.reshape(batch_size, seq_len, -1)
        logvar = logvar.reshape(batch_size, seq_len, -1)
        return mu, logvar

    def decode_sequence(self, z_seq):
        batch_size, seq_len, latent_dim = z_seq.shape
        z_flat = z_seq.reshape(-1, latent_dim)
        out_flat = self.decoder(z_flat)
        out_seq = out_flat.reshape(batch_size, seq_len, -1)
        return out_seq

    def forward(self, source_seq, target_seq=None, labels=None):
        mu, logvar = self.encode_sequence(source_seq)
        z = self.reparameterize(mu, logvar)
        target_out = self.decode_sequence(z)

        if target_seq is None or labels is None:
            return target_out

        losses = {}
        losses['kl'] = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
        losses['recon'] = F.mse_loss(target_out, target_seq)

        target_flat = target_seq.reshape(-1, self.target_dim)
        out_flat = target_out.reshape(-1, self.target_dim)
        losses['gan'] = -torch.mean(torch.log(self.frame_disc(out_flat) + 1e-8))

        real_logits = self.seq_disc(target_seq)
        fake_logits = self.seq_disc(target_out.detach())
        fake_target = torch.full_like(labels, config.NUM_EMOTIONS)

        losses['seqdis'] = F.cross_entropy(real_logits, labels) + \
                           F.cross_entropy(fake_logits, fake_target)

        return target_out, losses


class ModalityTransformer(nn.Module):
    def __init__(self, input_dim, d_model, nhead, num_layers=2):
        super().__init__()
        self.input_proj = nn.Linear(input_dim, d_model)
        self.pos_encoder = PositionalEncoding(d_model)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=d_model*4,
            dropout=0.1,
            batch_first=True,
            activation='gelu'
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.output_proj = nn.Linear(d_model, d_model)
        self.norm = nn.LayerNorm(d_model)

    def forward(self, x):
        x = self.input_proj(x)
        x = self.pos_encoder(x)
        x = self.transformer(x)
        x = self.norm(x)
        x = self.output_proj(x)
        return x


class CrossModalAttention(nn.Module):
    def __init__(self, d_model, nhead):
        super().__init__()
        self.cross_attn = nn.MultiheadAttention(
            d_model, nhead, batch_first=True, dropout=0.1
        )
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)

        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_model*4),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(d_model*4, d_model)
        )

    def forward(self, query, key, value):
        attn_out, _ = self.cross_attn(query, key, value)
        x = self.norm1(query + attn_out)
        ffn_out = self.ffn(x)
        x = self.norm2(x + ffn_out)
        return x


class MultimodalFusion(nn.Module):
    def __init__(self, d_model, nhead):
        super().__init__()

        self.av = CrossModalAttention(d_model, nhead)
        self.at = CrossModalAttention(d_model, nhead)
        self.va = CrossModalAttention(d_model, nhead)
        self.vt = CrossModalAttention(d_model, nhead)
        self.ta = CrossModalAttention(d_model, nhead)
        self.tv = CrossModalAttention(d_model, nhead)

        self.fusion = ModalityTransformer(d_model*3, d_model*3, nhead, 2)
        self.weights = nn.Parameter(torch.ones(3) * 0.33)

    def forward(self, a, v, t):
        a_to_v = self.av(a, v, v)
        a_to_t = self.at(a, t, t)
        v_to_a = self.va(v, a, a)
        v_to_t = self.vt(v, t, t)
        t_to_a = self.ta(t, a, a)
        t_to_v = self.tv(t, v, v)

        a_fused = self.weights[0] * (a + a_to_v + a_to_t) / 3
        v_fused = self.weights[1] * (v + v_to_a + v_to_t) / 3
        t_fused = self.weights[2] * (t + t_to_a + t_to_v) / 3

        a_pooled = a_fused.mean(dim=1)
        v_pooled = v_fused.mean(dim=1)
        t_pooled = t_fused.mean(dim=1)

        fused = torch.cat([a_pooled, v_pooled, t_pooled], dim=-1)
        fused = fused.unsqueeze(1)
        fused = self.fusion(fused)
        fused = fused.squeeze(1)

        return fused


class MultimodalEmotionRecognizer(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.audio_transformer = ModalityTransformer(
            config.AUDIO_FEAT_DIM, config.HIDDEN_DIM, config.NUM_HEADS
        )
        self.visual_transformer = ModalityTransformer(
            config.VISUAL_FEAT_DIM, config.HIDDEN_DIM, config.NUM_HEADS
        )
        self.text_transformer = ModalityTransformer(
            config.TEXT_FEAT_DIM, config.HIDDEN_DIM, config.NUM_HEADS
        )

        self.fusion = MultimodalFusion(config.HIDDEN_DIM, config.NUM_HEADS)

        self.classifier = nn.Sequential(
            nn.Linear(config.HIDDEN_DIM * 3, config.HIDDEN_DIM * 2),
            nn.LayerNorm(config.HIDDEN_DIM * 2),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(config.HIDDEN_DIM * 2, config.HIDDEN_DIM),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(config.HIDDEN_DIM, config.NUM_EMOTIONS)
        )

    def forward(self, audio, visual, text):
        a_out = self.audio_transformer(audio)
        v_out = self.visual_transformer(visual)
        t_out = self.text_transformer(text)

        fused = self.fusion(a_out, v_out, t_out)
        output = self.classifier(fused)

        return output


class CompletePaperModel(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.shared_encoders = nn.ModuleDict({
            'v': VAEEncoder(config.VISUAL_FEAT_DIM, config.LATENT_DIM_VAE),
            'a': VAEEncoder(config.AUDIO_FEAT_DIM, config.LATENT_DIM_VAE),
            't': VAEEncoder(config.TEXT_FEAT_DIM, config.LATENT_DIM_VAE)
        })

        print("\nCreating shared decoders:")
        self.shared_decoders = nn.ModuleDict({
            'v': VAEDecoder(config.LATENT_DIM_VAE, config.VISUAL_FEAT_DIM),
            'a': VAEDecoder(config.LATENT_DIM_VAE, config.AUDIO_FEAT_DIM),
            't': VAEDecoder(config.LATENT_DIM_VAE, config.TEXT_FEAT_DIM)
        })
        print(" Visual decoder (shared)")
        print(" Audio decoder (shared)")
        print(" Text decoder (shared)")

        # Create 6 translators
        print("\nCreating 6 VAEGAN translators:")
        self.translators = nn.ModuleDict({
            'v2a': VAEGANTranslator(config.VISUAL_FEAT_DIM, config.AUDIO_FEAT_DIM,
                                   config.LATENT_DIM_VAE, config.NUM_EMOTIONS,
                                   self.shared_encoders['v'], self.shared_decoders['a'], "v2a"),
            'a2v': VAEGANTranslator(config.AUDIO_FEAT_DIM, config.VISUAL_FEAT_DIM,
                                   config.LATENT_DIM_VAE, config.NUM_EMOTIONS,
                                   self.shared_encoders['a'], self.shared_decoders['v'], "a2v"),
            'v2t': VAEGANTranslator(config.VISUAL_FEAT_DIM, config.TEXT_FEAT_DIM,
                                   config.LATENT_DIM_VAE, config.NUM_EMOTIONS,
                                   self.shared_encoders['v'], self.shared_decoders['t'], "v2t"),
            't2v': VAEGANTranslator(config.TEXT_FEAT_DIM, config.VISUAL_FEAT_DIM,
                                   config.LATENT_DIM_VAE, config.NUM_EMOTIONS,
                                   self.shared_encoders['t'], self.shared_decoders['v'], "t2v"),
            'a2t': VAEGANTranslator(config.AUDIO_FEAT_DIM, config.TEXT_FEAT_DIM,
                                   config.LATENT_DIM_VAE, config.NUM_EMOTIONS,
                                   self.shared_encoders['a'], self.shared_decoders['t'], "a2t"),
            't2a': VAEGANTranslator(config.TEXT_FEAT_DIM, config.AUDIO_FEAT_DIM,
                                   config.LATENT_DIM_VAE, config.NUM_EMOTIONS,
                                   self.shared_encoders['t'], self.shared_decoders['a'], "t2a")
        })

        print("\n All 6 translators created with weight sharing")

        # Emotion recognizer
        self.recognizer = MultimodalEmotionRecognizer(config)
        self.to(config.DEVICE)

    def compute_translator_losses(self, features, labels):
        total_loss = 0
        losses = {'kl': 0, 'recon': 0, 'gan': 0, 'seqdis': 0, 'cycle': 0}

        modalities = list(features.keys())

        for src in modalities:
            for tgt in modalities:
                if src == tgt:
                    continue

                translator = self.translators[f'{src}2{tgt}']
                target_out, trans_losses = translator(features[src], features.get(tgt), labels)

                for k, v in trans_losses.items():
                    losses[k] += v

                if f'{tgt}2{src}' in self.translators and tgt in features:
                    source_recon = self.translators[f'{tgt}2{src}'](target_out)
                    losses['cycle'] += F.mse_loss(source_recon, features[src]) * self.config.CYCLE_WEIGHT

        total_loss = (self.config.VAE_WEIGHT * losses['kl'] +
                     self.config.VAE_WEIGHT * losses['recon'] +
                     self.config.GAN_WEIGHT * losses['gan'] +
                     self.config.SEQDIS_WEIGHT * losses['seqdis'] +
                     losses['cycle'])

        return total_loss, losses

    def augment_missing_modalities(self, features):
        augmented = features.copy()

        if 'v' in features:
            if 'a' not in features:
                augmented['a'] = self.translators['v2a'](features['v'])
            if 't' not in features:
                augmented['t'] = self.translators['v2t'](features['v'])

        if 'a' in features:
            if 'v' not in features:
                augmented['v'] = self.translators['a2v'](features['a'])
            if 't' not in features:
                augmented['t'] = self.translators['a2t'](features['a'])

        if 't' in features:
            if 'v' not in features:
                augmented['v'] = self.translators['t2v'](features['t'])
            if 'a' not in features:
                augmented['a'] = self.translators['t2a'](features['t'])

        return augmented

    def forward(self, audio=None, visual=None, text=None, labels=None, mode='classify'):
        features = {}
        if audio is not None:
            features['a'] = audio
        if visual is not None:
            features['v'] = visual
        if text is not None:
            features['t'] = text

        if mode == 'translate':
            if not features or labels is None:
                return torch.tensor(0.0).to(self.config.DEVICE), {}
            return self.compute_translator_losses(features, labels)

        elif mode == 'classify':
            if labels is not None and len(features) < 3:
                features = self.augment_missing_modalities(features)

            batch_size = labels.size(0) if labels is not None else 1
            device = audio.device if audio is not None else self.config.DEVICE

            a_feat = features.get('a', torch.zeros(batch_size, 1, self.config.AUDIO_FEAT_DIM).to(device))
            v_feat = features.get('v', torch.zeros(batch_size, 1, self.config.VISUAL_FEAT_DIM).to(device))
            t_feat = features.get('t', torch.zeros(batch_size, 1, self.config.TEXT_FEAT_DIM).to(device))

            return self.recognizer(a_feat, v_feat, t_feat)

        else:
            logits = self.forward(audio, visual, text, labels, mode='classify')
            trans_loss, loss_components = self.forward(audio, visual, text, labels, mode='translate')
            return logits, trans_loss, loss_components

class PaperTrainer:
    def __init__(self, model, config,
                 visual_extractor=None, audio_extractor=None, text_extractor=None):
        self.model = model
        self.config = config
        self.visual_extractor = visual_extractor
        self.audio_extractor = audio_extractor
        self.text_extractor = text_extractor

        self.model = self.model.to(config.DEVICE)

        self.optimizer = optim.AdamW(
            model.parameters(),
            lr=config.LEARNING_RATE,
            weight_decay=0.01,
            betas=(0.5, 0.999)
        )

        self.scheduler = ReduceLROnPlateau(
            self.optimizer, mode='max', factor=0.5, patience=5
        )

        self.criterion = nn.CrossEntropyLoss()
        self.scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None

        self.history = {
            'train_loss': [], 'train_acc': [],
            'val_loss': [], 'val_acc': [], 'val_f1': [],
            'kl_loss': [], 'recon_loss': [], 'gan_loss': [],
            'seqdis_loss': [], 'cycle_loss': []
        }
        self.best_val_acc = 0
        self.step = 0

    def extract_batch_features(self, batch):
        """Extract features for a batch using real data"""
        batch_size = len(batch['video_id'])
        device = self.config.DEVICE

        visual_features = torch.zeros(
            (batch_size, self.config.MAX_SEQ_LEN, self.config.VISUAL_FEAT_DIM),
            device=device
        )
        audio_features = torch.zeros(
            (batch_size, self.config.MAX_SEQ_LEN, self.config.AUDIO_FEAT_DIM),
            device=device
        )
        text_features = torch.zeros(
            (batch_size, self.config.MAX_SEQ_LEN, self.config.TEXT_FEAT_DIM),
            device=device
        )

        for i in range(batch_size):
            # Visual features
            if self.visual_extractor and batch['video_path'][i] and os.path.exists(batch['video_path'][i]):
                try:
                    vis = self.visual_extractor.extract_video_features(
                        batch['video_path'][i], self.config.MAX_SEQ_LEN
                    )
                    visual_features[i] = torch.FloatTensor(vis).to(device)
                except Exception as e:
                    print(f"    Visual extraction error: {e}")

            # Audio features
            if self.audio_extractor and batch['audio_path'][i] and os.path.exists(batch['audio_path'][i]):
                try:
                    aud = self.audio_extractor.extract_audio_features(
                        batch['audio_path'][i], self.config.MAX_SEQ_LEN
                    )
                    audio_features[i] = torch.FloatTensor(aud).to(device)
                except Exception as e:
                    print(f"    Audio extraction error: {e}")

            # Text features
            if self.text_extractor and batch['transcript_path'][i] and os.path.exists(batch['transcript_path'][i]):
                try:
                    with open(batch['transcript_path'][i], 'r', encoding='utf-8', errors='ignore') as f:
                        transcript = f.read()
                    txt = self.text_extractor.extract_text_features(
                        transcript, self.config.MAX_SEQ_LEN
                    )
                    text_features[i] = torch.FloatTensor(txt).to(device)
                except Exception as e:
                    print(f"    Text extraction error: {e}")

        return visual_features, audio_features, text_features

    def train_epoch(self, loader, epoch):
        self.model.train()
        total_loss = 0
        correct = 0
        total = 0
        comp_losses = {'kl': 0, 'recon': 0, 'gan': 0, 'seqdis': 0, 'cycle': 0}

        pbar = tqdm(loader, desc=f'Epoch {epoch}')
        self.optimizer.zero_grad()

        for batch_idx, batch in enumerate(pbar):
            self.step += 1

            # Extract features from real data
            visual, audio, text = self.extract_batch_features(batch)
            labels = batch['label'].to(self.config.DEVICE)

            # E2E ratio training
            if self.step % self.config.E2E_RATIO == 0:
                # Update translators
                if self.scaler:
                    with torch.cuda.amp.autocast():
                        _, trans_loss, losses = self.model(
                            audio, visual, text, labels, mode='full'
                        )
                        loss = trans_loss

                    self.scaler.scale(loss).backward()

                    for k, v in losses.items():
                        if isinstance(v, torch.Tensor):
                            comp_losses[k] += v.item()
                else:
                    _, trans_loss, losses = self.model(
                        audio, visual, text, labels, mode='full'
                    )
                    loss = trans_loss
                    loss.backward()

                    for k, v in losses.items():
                        if isinstance(v, torch.Tensor):
                            comp_losses[k] += v.item()
            else:
                # Update classifier
                if self.scaler:
                    with torch.cuda.amp.autocast():
                        logits = self.model(audio, visual, text, labels, mode='classify')
                        loss = self.criterion(logits, labels)

                    self.scaler.scale(loss).backward()
                else:
                    logits = self.model(audio, visual, text, labels, mode='classify')
                    loss = self.criterion(logits, labels)
                    loss.backward()

                _, predicted = logits.max(1)
                total += labels.size(0)
                correct += predicted.eq(labels).sum().item()

            # Gradient accumulation
            if (batch_idx + 1) % 2 == 0:
                if self.scaler:
                    self.scaler.unscale_(self.optimizer)
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.config.GRADIENT_CLIP)
                    self.scaler.step(self.optimizer)
                    self.scaler.update()
                else:
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.config.GRADIENT_CLIP)
                    self.optimizer.step()

                self.optimizer.zero_grad()

            total_loss += loss.item()

            gpu_mem = f'{torch.cuda.memory_allocated()/1e9:.2f}GB' if torch.cuda.is_available() else 'N/A'
            pbar.set_postfix({
                'loss': f'{total_loss/(batch_idx+1):.4f}',
                'acc': f'{100.*correct/max(1,total):.2f}%',
                'gpu_mem': gpu_mem,
                'mode': 'TRANS' if self.step % self.config.E2E_RATIO == 0 else 'CLASS'
            })

        for k in comp_losses:
            if len(loader) > 0:                self.history[f'{k}_loss'].append(comp_losses[k] / len(loader))

        return total_loss/len(loader), 100.*correct/max(1,total)

    @torch.no_grad()
    def validate(self, loader):
        self.model.eval()
        correct = 0
        total = 0
        all_preds = []
        all_labels = []

        for batch in tqdm(loader, desc='Validating'):
            visual, audio, text = self.extract_batch_features(batch)
            labels = batch['label'].to(self.config.DEVICE)

            logits = self.model(audio, visual, text, labels, mode='classify')
            _, predicted = logits.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

        accuracy = 100. * correct / total
        f1 = f1_score(all_labels, all_preds, average='weighted', zero_division=0)

        return accuracy, f1

    def train(self, train_loader, val_loader, epochs):
        for epoch in range(epochs):
            print(f"Epoch {epoch+1}/{epochs}")
            print(f"E2E Ratio: 1:{self.config.E2E_RATIO}")
            if torch.cuda.is_available():
                print(f"GPU Memory: {torch.cuda.memory_allocated()/1e9:.2f}GB")

            train_loss, train_acc = self.train_epoch(train_loader, epoch+1)
            val_acc, val_f1 = self.validate(val_loader)

            self.scheduler.step(val_acc)

            self.history['train_loss'].append(train_loss)
            self.history['train_acc'].append(train_acc)
            self.history['val_acc'].append(val_acc)
            self.history['val_f1'].append(val_f1)

            print(f"\nTrain Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%")
            print(f"Val Acc: {val_acc:.2f}%, Val F1: {val_f1:.4f}")

            if val_acc > self.best_val_acc:
                self.best_val_acc = val_acc
                torch.save(self.model.state_dict(), 'best_model_real.pth')
                print(f"\n New best model saved! Acc: {val_acc:.2f}%")

            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                gc.collect()

        return self.history


def main():
    print(f"Dataset path: {config.BASE_PATH}")

    # Initialize feature extractors
    print("\nInitializing feature extractors")
    visual_extractor = FANFeatureExtractor(config.DEVICE)
    audio_extractor = PANNsFeatureExtractor(config.DEVICE)
    text_extractor = GloVeFeatureExtractor()

    # Create datasets
    print("\nLoading CMU-MOSI dataset")
    train_dataset = CMUMOSIDataset(config.BASE_PATH, 'train', config.MAX_SEQ_LEN)
    val_dataset = CMUMOSIDataset(config.BASE_PATH, 'val', config.MAX_SEQ_LEN)

    print(f"\nTrain samples: {len(train_dataset)}")
    print(f"Val samples: {len(val_dataset)}")

    if len(train_dataset) == 0:
        print("\n No samples found! Check your dataset path.")
        return

    # Create data loaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=config.BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=True,
        collate_fn=collate_fn
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=config.BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=True,
        collate_fn=collate_fn
    )

    print(f"\nTrain batches: {len(train_loader)}")
    print(f"Val batches: {len(val_loader)}")

    # Create model
    model = CompletePaperModel(config)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"\nTotal parameters: {total_params:,}")

    # Train
    print(f"\nStarting training for {config.NUM_EPOCHS} epochs...")
    trainer = PaperTrainer(
        model, config,
        visual_extractor=visual_extractor,
        audio_extractor=audio_extractor,
        text_extractor=text_extractor
    )

    history = trainer.train(train_loader, val_loader, config.NUM_EPOCHS)

    # Plot results
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.plot(history['train_loss'], label='Train')
    plt.title('Training Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history['train_acc'], label='Train')
    plt.plot(history['val_acc'], label='Val')
    plt.title('Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy (%)')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.savefig('real_data_training.png')
    plt.show()

    print(f"\n{'='*70}")
    print("Training Complete!")
    print(f"Best Validation Accuracy: {max(history['val_acc']):.2f}%")
    print(f"Best Validation F1: {max(history['val_f1']):.4f}")
    print(f"{'='*70}")


if __name__ == "__main__":
    torch.manual_seed(42)
    random.seed(42)
    np.random.seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(42)

    main()